import json

# New keys for zh.json
zh_new_keys = {
    # analysis.py - life_stage
    "analysis_stage_childhood": "童年 / 基础打底期",
    "analysis_stage_student": "学生 / 青春探索期",
    "analysis_stage_early_career": "初入社会 / 打怪升级期",
    "analysis_stage_career_dev": "事业发展 / 定位期",
    "analysis_stage_midlife": "中年调整 / 结构升级期",
    "analysis_stage_mature": "成熟收成 / 布局期",
    "analysis_stage_later_years": "晚年享受 / 传承期",
    "analysis_stage_retirement": "养生慢活 / 回顾期",
    # analysis.py - DAYUN_TPL
    "dayun_tpl_help_0": "这一运贵人明显，适合主动出击，多去结识新圈子、上新项目。只要你肯迈开步，机会就会自己浮上来。",
    "dayun_tpl_help_1": "整体顺势而上，资源、人脉都更愿意靠近你。适合换赛道、升学深造、跳槽到更大的平台。",
    "dayun_tpl_help_2": "适合把之前积累的东西拿出来用，用好贵人和平台，多去争取头衔、证书、职级上的抬升。",
    "dayun_tpl_self_0": "这一运自我意识变强，会更想按自己的想法活。适合确立个人风格、IP 或职业方向，但不要把所有桥都烧掉。",
    "dayun_tpl_self_1": "会有『我就想试一次』的冲动，适合创业、副业、转专业，但务必保留一点安全垫。",
    "dayun_tpl_self_2": "容易形成自己的一套价值观，与家庭或环境有些观念拉扯，要学会在坚持和妥协之间找平衡。",
    "dayun_tpl_attack_0": "这是竞争味道很重的一运，容易面对考试、升职、业绩指标或职场斗争。适合冲刺，但要学会用策略而不是硬刚。",
    "dayun_tpl_attack_1": "外部环境会逼你成长，可能出现换工作、换城市、换圈子等关键节点，趁机修炼谈判力与边界感。",
    "dayun_tpl_attack_2": "适合主动争取位置，尤其是想走管理、业务一线、业绩导向岗位的，会有比较多打仗的机会。",
    "dayun_tpl_drain_0": "这一运更像『蓄力期』，付出会多于及时回报。适合学习、修行、建作品集，把时间花在能沉淀的东西上。",
    "dayun_tpl_drain_1": "生活节奏可能有点忙乱，容易一心多用。要学会取舍，不要什么都想兼顾，否则身心容易透支。",
    "dayun_tpl_drain_2": "适合默默打基础：读书、考证、练技能、调整体质。短期看不出效果，但会在下一两运慢慢体现出来。",
    "dayun_tpl_stress_0": "责任感会被强行拉满，可能要照顾家人、扛家庭经济、面对长期的工作压力。宜稳守，不宜乱赌一把。",
    "dayun_tpl_stress_1": "这一运容易被现实拽着走，内心压力大时，记得定期运动、倾诉，避免情绪积压变成身体问题。",
    "dayun_tpl_stress_2": "规则和制度感会变强，适合学会在系统里玩游戏——懂流程、懂汇报、懂如何保护自己。",
    "dayun_tpl_neutral_0": "整体比较平稳，不会特别大起大落。适合慢慢整理人生结构：钱、人、时间、健康都做一些微调。",
    "dayun_tpl_neutral_1": "这一运可以把节奏放得相对舒服，留一点空间给兴趣爱好，顺便看看有没有新的可能性冒出来。",
    "dayun_tpl_neutral_2": "适合做长期但不那么急的事：学一门新的语言、技术、乐器，或者养成真正对你有好处的习惯。",
    # analysis.py - dayun event hints
    "dayun_event_hint_childhood": " 多对应家庭环境、父母工作变动、搬家、升学等，对你的成长气氛影响大。",
    "dayun_event_hint_student": " 主要反映在学业、同学圈、人际关系以及早期恋爱体验上。",
    "dayun_event_hint_early_career": " 多与找工作、实习、踏入社会、第一次换工作或独立生活有关。",
    "dayun_event_hint_career_dev": " 容易出现事业方向调整、收入结构变化、成家立业等关键选择。",
    "dayun_event_hint_midlife": " 常见主题是家庭责任、房产、子女教育、事业定位再升级。",
    "dayun_event_hint_mature": " 更多体现在健康、生活质量、家庭氛围与内心状态的调整上。",
    # analysis.py - LIUNIAN_TPL
    "liunian_tpl_help_0": "人际助力明显，贵人、老师、上司或客户比较给力，适合主动提出自己的想法。",
    "liunian_tpl_help_1": "适合开启新计划：换专业、换组、换工作、搬家、留学等，都容易遇到愿意帮助你的人。",
    "liunian_tpl_help_2": "整体氛围偏顺，一些之前卡住的事情容易突然有突破口，可以多试几次。",
    "liunian_tpl_self_0": "自我意愿很强的一年，会特别在意『我真正想要什么』，适合做一些人生方向的决定。",
    "liunian_tpl_self_1": "更想按照自己节奏来，不太想被安排。注意和家人、同事在沟通方式上多一点温柔。",
    "liunian_tpl_self_2": "容易爆发个人表达欲：想做内容、想发声、想改变形象，是适合重塑自我标签的一年。",
    "liunian_tpl_attack_0": "竞争与对抗感偏重，可能遇到考试、升职、业绩压力，或者感情关系里的硬碰硬。",
    "liunian_tpl_attack_1": "需要多用策略而不是情绪，适合提升谈判、表达和边界感，学会说"不"。",
    "liunian_tpl_attack_2": "这一年适合去争，也适合认清哪些东西不值得你继续耗下去，做减法很重要。",
    "liunian_tpl_drain_0": "忙碌奔波，事情很多，容易觉得时间不够用。适合把精力集中在最重要的两三件事上。",
    "liunian_tpl_drain_1": "学习、考证、做项目、照顾家人等消耗型事务会比较多，别把自己排得太满。",
    "liunian_tpl_drain_2": "适合静下心来打磨技能或作品，短期虽然累，但对后面一两年很关键。",
    "liunian_tpl_stress_0": "责任和压力感偏重，容易被现实课题推着走：钱、健康、家人、合同等都要上心。",
    "liunian_tpl_stress_1": "如果身体开始发出信号（失眠、焦虑、暴饮暴食），要认真对待，必要时求助专业资源。",
    "liunian_tpl_stress_2": "外部要求高的一年，适合把基础打牢、把风险控制好，不太适合做大赌博式的决定。",
    "liunian_tpl_neutral_0": "整体起伏不大，生活比较按部就班。适合修复关系、整理房间和心情，给自己一点喘息空间。",
    "liunian_tpl_neutral_1": "可以用来尝试新兴趣、发展副业雏形，没那么多硬性考核，反而容易实验出新方向。",
    "liunian_tpl_neutral_2": "适合做年度复盘：看看哪些习惯值得保留，哪些人和事可以慢慢放下。",
    # analysis.py - liunian event hints
    "liunian_event_hint_child": " 主题多和读书、考试、同学、人际圈、兴趣班、搬家或父母工作变动有关。",
    "liunian_event_hint_youth": " 多和升学、求职、实习、初入社会、人际扩张、早期感情体验相关。",
    "liunian_event_hint_adult": " 容易遇到换工作、加薪、转方向、同居或结婚等关键现实选择。",
    "liunian_event_hint_middle": " 常见议题是事业稳定度、家庭结构、子女、房产和中期规划。",
    "liunian_event_hint_senior": " 多和资产配置、健康管理、子女发展、父母照护相关。",
    "liunian_event_hint_elderly": " 更看重生活质量、身体状态与精神愉悦，适合把节奏放慢一点。",
    # analysis.py - simple_shensha
    "shensha_text_taohua": "桃花：异性缘、人际魅力比较强，容易被注意到。",
    "shensha_text_wenchang": "文昌：头脑灵活，适合学习、写作、设计相关工作。",
    "shensha_text_yima": "驿马：一生不太安分，容易搬家、换环境、出差或留学。",
    "shensha_text_huagai": "华盖：思考多，比较有主见，也有点孤高感，需要自己的空间。",
    "shensha_text_none": "命盘神煞分布比较平均，没有特别极端的加分或减分点，更看重自己后天的选择。",
    # analysis.py - analyze_profile
    "yang_label": "阳",
    "yin_label": "阴",
    "profile_dm_prefix": "日主为",
    "profile_personality_wood_base": "内在带着成长欲望和理想感，重视原则，有时比较直来直去。",
    "profile_personality_fire_base": "性格偏热情直接，情绪反应快，讲感觉，讨厌拖泥带水。",
    "profile_personality_earth_base": "偏稳重现实型，重视安全感与责任感，比较能扛事。",
    "profile_personality_metal_base": "思路偏理性、重规则，判断力强，喜欢清晰与效率。",
    "profile_personality_water_base": "感受细腻、观察力强，想法多，适合动脑而不是硬扛。",
    "profile_personality_default_base": "性格比较综合，不会特别偏向某一类。",
    "profile_personality_yang_ext": "整体偏外向、主动，遇事习惯先出手再慢慢调整。",
    "profile_personality_yin_ext": "整体偏含蓄、观察型，习惯先看清局势再出手。",
    "profile_career_wood": "适合教育、顾问、设计、文字、文化、心理、咨询等与成长相关的行业，也适合和人打交道的工作。",
    "profile_career_fire": "适合需要表现力和热情的工作：销售、公关、直播、自媒体、娱乐、餐饮、活动策划等。",
    "profile_career_earth": "适合稳定、需要耐心与责任感的岗位：行政、财务、人事、不动产、土木、供应链、后台运营等。",
    "profile_career_metal": "适合法律、金融、审计、IT 开发、数据分析、风控、管理岗位等需要判断和决策的工作。",
    "profile_career_water": "适合资讯、传媒、咨询、心理、外语、跨国业务、流通贸易等需要灵活沟通的领域。",
    "profile_career_default": "整体行业限制不大，重点是找能持续学习、又不会被完全绑死的方向。",
    "profile_love_wood_fire": "感情上比较主动，有感觉就很难装作没事，但也容易因为冲动或热度变化快而起伏较大。",
    "profile_love_metal_water": "感情里比较重理性与互动质量，不太喜欢黏腻，但希望对方能理解自己的节奏与边界。",
    "profile_love_earth": "感情观偏务实，比较看重稳定与长期打算，有时表达不够浪漫，但心里是记得对方好的。",
    "profile_health_fire": "注意心血管、血压与熬夜问题，保持规律作息很重要。",
    "profile_health_water": "注意肾脏、泌尿与睡眠质量，避免长期压力导致失眠。",
    "profile_health_wood": "注意肝胆与眼睛，用电脑时间长记得休息与运动。",
    "profile_health_metal": "注意呼吸道、皮肤与筋骨，久坐要时常活动。",
    "profile_health_earth": "注意脾胃、消化系统与体重管理，饮食尽量规律。",
    # comprehensive_analysis.py - get_life_stage
    "comp_stage_childhood": "童年基础期",
    "comp_stage_youth": "青春探索期",
    "comp_stage_social": "社会打怪期",
    "comp_stage_career": "事业发展期",
    "comp_stage_midlife": "中年调整期",
    "comp_stage_mature": "成熟收成期",
    "comp_stage_later": "晚年享受期",
    "comp_stage_retirement": "养生慢活期",
    # comprehensive_analysis.py - _get_likely_events
    "comp_events_help_0": "可能遇到贵人相助，获得好的机会",
    "comp_events_help_1": "适合开启新项目或尝试新事物",
    "comp_events_help_2": "人际关系顺利，容易得到支持",
    "comp_events_self_0": "可能会有个人成长的重要时刻",
    "comp_events_self_1": "适合确立自己的目标和方向",
    "comp_events_self_2": "可能会遇到一些挑战但能克服",
    "comp_events_drain_0": "可能会感到忙碌，事情较多",
    "comp_events_drain_1": "适合学习新技能，为未来做准备",
    "comp_events_drain_2": "需要耐心，成果会慢慢显现",
    "comp_events_attack_0": "可能会遇到竞争或挑战",
    "comp_events_attack_1": "适合提升自己的实力",
    "comp_events_attack_2": "需要处理好人际关系",
    "comp_events_stress_0": "可能会遇到一些压力或困难",
    "comp_events_stress_1": "需要保持积极心态",
    "comp_events_stress_2": "适合稳扎稳打，不要冲动",
    "comp_events_neutral_0": "生活按部就班，不会有大的波动",
    "comp_events_neutral_1": "适合做一些日常的事情",
    "comp_events_neutral_2": "保持平常心就好",
    # comprehensive_analysis.py - _get_watch_out
    "comp_watch_help_0": "虽然运势好，但不要过于自信",
    "comp_watch_help_1": "珍惜帮助你的人，不要过河拆桥",
    "comp_watch_help_2": "好运时也要保持谦虚",
    "comp_watch_self_0": "不要过于固执，要学会倾听他人",
    "comp_watch_self_1": "保持开放心态，接受不同意见",
    "comp_watch_self_2": "注意与家人朋友的沟通",
    "comp_watch_drain_0": "不要因为忙碌而忽视健康",
    "comp_watch_drain_1": "学会取舍，不要什么都想做",
    "comp_watch_drain_2": "保持耐心，不要急于求成",
    "comp_watch_attack_0": "注意处理好人际关系",
    "comp_watch_attack_1": "不要冲动做决定",
    "comp_watch_attack_2": "保持冷静，理性分析",
    "comp_watch_stress_0": "注意身体健康，定期体检",
    "comp_watch_stress_1": "不要给自己太大压力",
    "comp_watch_stress_2": "学会释放压力，保持心情愉悦",
    "comp_watch_neutral_0": "保持良好的生活习惯",
    "comp_watch_neutral_1": "不要因为平淡而懈怠",
    "comp_watch_neutral_2": "持续学习，提升自己",
    # comprehensive_analysis.py - _get_what_to_do
    "comp_do_help_0": "主动出击，抓住机会",
    "comp_do_help_1": "拓展人脉，结交新朋友",
    "comp_do_help_2": "尝试新事物，挑战自己",
    "comp_do_self_0": "确立自己的目标和方向",
    "comp_do_self_1": "保持自我，不要随波逐流",
    "comp_do_self_2": "提升自己的专业能力",
    "comp_do_drain_0": "学习新技能，为未来做准备",
    "comp_do_drain_1": "保持耐心，稳扎稳打",
    "comp_do_drain_2": "做好时间管理，提高效率",
    "comp_do_attack_0": "提升自己的实力",
    "comp_do_attack_1": "处理好人际关系",
    "comp_do_attack_2": "保持冷静，理性决策",
    "comp_do_stress_0": "保持积极心态",
    "comp_do_stress_1": "注意身体健康",
    "comp_do_stress_2": "稳扎稳打，不要冲动",
    "comp_do_neutral_0": "保持良好的生活习惯",
    "comp_do_neutral_1": "持续学习，提升自己",
    "comp_do_neutral_2": "珍惜身边的人",
}

# New keys for en.json
en_new_keys = {
    # analysis.py - life_stage
    "analysis_stage_childhood": "Childhood / Foundation",
    "analysis_stage_student": "Student / Youth Exploration",
    "analysis_stage_early_career": "Early Career / Getting Started",
    "analysis_stage_career_dev": "Career Development / Positioning",
    "analysis_stage_midlife": "Midlife Adjustment / Upgrading",
    "analysis_stage_mature": "Mature / Harvesting",
    "analysis_stage_later_years": "Later Years / Legacy",
    "analysis_stage_retirement": "Retirement / Reflection",
    # analysis.py - DAYUN_TPL
    "dayun_tpl_help_0": "This period has strong nobleman luck. Take initiative, meet new circles, start new projects. Opportunities will come if you step forward.",
    "dayun_tpl_help_1": "Riding the favorable trend, resources and connections are drawn to you. Good for changing tracks, further education, or moving to a bigger platform.",
    "dayun_tpl_help_2": "Time to use what you've accumulated. Leverage noble help and platforms to pursue titles, certifications, and promotions.",
    "dayun_tpl_self_0": "Self-awareness strengthens in this period. You'll want to live by your own rules. Good for establishing personal style, IP, or career direction, but don't burn all bridges.",
    "dayun_tpl_self_1": "You'll feel an impulse to 'try it once.' Good for starting businesses, side projects, or changing majors, but keep a safety cushion.",
    "dayun_tpl_self_2": "You may form your own value system, creating tension with family or environment. Learn to balance persistence with compromise.",
    "dayun_tpl_attack_0": "A highly competitive period with exams, promotions, performance targets, or workplace struggles. Sprint but use strategy, not brute force.",
    "dayun_tpl_attack_1": "External pressure forces growth. Job changes, city moves, or social circle shifts may occur. Use this to develop negotiation skills and boundaries.",
    "dayun_tpl_attack_2": "Good for actively seeking positions, especially in management, frontline business, or performance-oriented roles.",
    "dayun_tpl_drain_0": "This is more of a 'power accumulation' period. Efforts may exceed immediate rewards. Good for learning, practice, and building a portfolio.",
    "dayun_tpl_drain_1": "Life may feel hectic and scattered. Learn to prioritize — trying to handle everything at once leads to burnout.",
    "dayun_tpl_drain_2": "Good for quietly building foundations: reading, certifications, skills, health adjustments. Short-term gains may be invisible but will manifest in the next 1-2 periods.",
    "dayun_tpl_stress_0": "Responsibilities are forced upon you — family care, household finances, long-term work pressure. Stay steady, don't gamble recklessly.",
    "dayun_tpl_stress_1": "Reality pulls you along. When inner pressure builds, exercise regularly, talk to someone, and prevent emotional buildup from becoming physical problems.",
    "dayun_tpl_stress_2": "Rules and systems become more prominent. Learn to navigate within systems — understand processes, reporting, and self-protection.",
    "dayun_tpl_neutral_0": "Relatively stable overall, no extreme highs or lows. Good for gradually restructuring life: money, people, time, and health adjustments.",
    "dayun_tpl_neutral_1": "Pace can be more comfortable. Leave room for hobbies and interests while exploring new possibilities that may emerge.",
    "dayun_tpl_neutral_2": "Good for long-term but not urgent pursuits: learning a new language, skill, instrument, or developing truly beneficial habits.",
    # analysis.py - dayun event hints
    "dayun_event_hint_childhood": " Mostly relates to family environment, parental job changes, moves, and school transitions — significant impact on growth atmosphere.",
    "dayun_event_hint_student": " Mainly reflected in academics, peer circles, relationships, and early romantic experiences.",
    "dayun_event_hint_early_career": " Mostly related to job hunting, internships, entering society, first job change, or independent living.",
    "dayun_event_hint_career_dev": " Career direction adjustments, income structure changes, and settling down are key choices that may arise.",
    "dayun_event_hint_midlife": " Common themes include family responsibilities, housing, children's education, and career repositioning.",
    "dayun_event_hint_mature": " More reflected in health, quality of life, family atmosphere, and inner state adjustments.",
    # analysis.py - LIUNIAN_TPL
    "liunian_tpl_help_0": "Strong interpersonal support — noble people, teachers, bosses, or clients are helpful. Good for presenting your ideas.",
    "liunian_tpl_help_1": "Good for starting new plans: changing majors, teams, jobs, moving, or studying abroad. You'll easily find people willing to help.",
    "liunian_tpl_help_2": "Overall favorable atmosphere. Things that were stuck may suddenly break through. Try multiple times.",
    "liunian_tpl_self_0": "Strong self-will year. You'll focus on 'what I truly want.' Good for making life direction decisions.",
    "liunian_tpl_self_1": "You want to follow your own pace and resist being arranged. Be gentler in communication with family and colleagues.",
    "liunian_tpl_self_2": "Personal expression may explode: creating content, speaking out, changing image. A good year to reshape your personal brand.",
    "liunian_tpl_attack_0": "Competition and confrontation are prominent. Exams, promotions, performance pressure, or relationship conflicts may arise.",
    "liunian_tpl_attack_1": "Use strategy over emotion. Improve negotiation, expression, and boundary-setting skills. Learn to say 'no.'",
    "liunian_tpl_attack_2": "Good year to fight for what you want, and also to recognize what's not worth your energy. Subtraction is important.",
    "liunian_tpl_drain_0": "Busy and rushed, with many tasks. Feeling short on time. Focus energy on the 2-3 most important things.",
    "liunian_tpl_drain_1": "Study, certifications, projects, and family care will consume much energy. Don't over-schedule yourself.",
    "liunian_tpl_drain_2": "Good for quietly honing skills or works. Tiring in the short term but critical for the next 1-2 years.",
    "liunian_tpl_stress_0": "Responsibility and pressure are heavy. Reality pushes you: money, health, family, contracts all demand attention.",
    "liunian_tpl_stress_1": "If your body signals trouble (insomnia, anxiety, binge eating), take it seriously. Seek professional help when needed.",
    "liunian_tpl_stress_2": "High external demands. Good for building strong foundations and controlling risk. Not ideal for big gambles.",
    "liunian_tpl_neutral_0": "Relatively stable, life follows routine. Good for repairing relationships, organizing space and emotions, giving yourself breathing room.",
    "liunian_tpl_neutral_1": "Try new interests, develop side project ideas. Without rigid evaluations, it's easier to experiment with new directions.",
    "liunian_tpl_neutral_2": "Good for annual review: see which habits are worth keeping, and which people and things to gradually let go.",
    # analysis.py - liunian event hints
    "liunian_event_hint_child": " Themes revolve around studying, exams, classmates, social circles, hobbies, moves, or parental job changes.",
    "liunian_event_hint_youth": " Mostly related to further education, job hunting, internships, entering society, social expansion, and early romance.",
    "liunian_event_hint_adult": " Job changes, raises, direction shifts, cohabitation, or marriage — key real-life choices may arise.",
    "liunian_event_hint_middle": " Common topics include career stability, family structure, children, housing, and medium-term planning.",
    "liunian_event_hint_senior": " Mostly related to asset allocation, health management, children's development, and elderly care.",
    "liunian_event_hint_elderly": " Focus more on quality of life, physical condition, and mental well-being. Good for slowing down.",
    # analysis.py - simple_shensha
    "shensha_text_taohua": "Peach Blossom: Strong opposite-sex charm and interpersonal appeal, easily noticed.",
    "shensha_text_wenchang": "Academic Star: Sharp mind, suited for learning, writing, and design work.",
    "shensha_text_yima": "Traveling Horse: Restless life, prone to moves, environment changes, business trips, or studying abroad.",
    "shensha_text_huagai": "Elegant Seal: Deep thinker with strong opinions, a touch of aloofness, needs personal space.",
    "shensha_text_none": "No extreme symbolic stars in your chart. Distribution is balanced. Success depends more on your own efforts.",
    # analysis.py - analyze_profile
    "yang_label": "Yang",
    "yin_label": "Yin",
    "profile_dm_prefix": "Day Master: ",
    "profile_personality_wood_base": "Inner drive for growth and ideals, values principles, sometimes straightforward.",
    "profile_personality_fire_base": "Warm and direct personality, quick emotional reactions, values feeling, dislikes dragging things out.",
    "profile_personality_earth_base": "Steady and realistic type, values security and responsibility, can handle pressure.",
    "profile_personality_metal_base": "Rational and rule-oriented thinking, strong judgment, prefers clarity and efficiency.",
    "profile_personality_water_base": "Sensitive and perceptive, many ideas, better at thinking than brute-forcing.",
    "profile_personality_default_base": "Relatively balanced personality, not strongly inclined toward any particular type.",
    "profile_personality_yang_ext": "Outgoing and proactive overall, tends to act first and adjust later.",
    "profile_personality_yin_ext": "Reserved and observant overall, tends to assess the situation before acting.",
    "profile_career_wood": "Suited for education, consulting, design, writing, culture, psychology, and people-oriented work.",
    "profile_career_fire": "Suited for work requiring expressiveness and passion: sales, PR, livestreaming, media, entertainment, catering, event planning.",
    "profile_career_earth": "Suited for stable roles requiring patience and responsibility: admin, finance, HR, real estate, civil engineering, logistics, back-office.",
    "profile_career_metal": "Suited for law, finance, auditing, IT development, data analysis, risk management — roles requiring judgment and decisions.",
    "profile_career_water": "Suited for media, consulting, psychology, foreign languages, international business, trade — fields requiring flexible communication.",
    "profile_career_default": "Industry restrictions are minimal. Focus on finding a direction where you can continuously learn without being completely bound.",
    "profile_love_wood_fire": "Proactive in love — hard to hide feelings when attracted, but prone to ups and downs from impulsiveness or changing passion.",
    "profile_love_metal_water": "Values rationality and interaction quality in love, doesn't like clinginess, but hopes partners understand their rhythm and boundaries.",
    "profile_love_earth": "Practical love style, values stability and long-term planning. May not be romantic in expression but genuinely cares.",
    "profile_health_fire": "Watch cardiovascular health, blood pressure, and late nights. Maintaining regular sleep is important.",
    "profile_health_water": "Watch kidneys, urinary system, and sleep quality. Avoid long-term stress leading to insomnia.",
    "profile_health_wood": "Watch liver/gallbladder and eyes. Take breaks and exercise when using computers for long periods.",
    "profile_health_metal": "Watch respiratory system, skin, and bones. Move regularly when sitting for long periods.",
    "profile_health_earth": "Watch spleen/stomach, digestive system, and weight management. Keep diet regular.",
    # comprehensive_analysis.py - get_life_stage
    "comp_stage_childhood": "Childhood",
    "comp_stage_youth": "Youth",
    "comp_stage_social": "Entering Society",
    "comp_stage_career": "Career Growth",
    "comp_stage_midlife": "Midlife Adjustment",
    "comp_stage_mature": "Maturity",
    "comp_stage_later": "Later Years",
    "comp_stage_retirement": "Retirement",
    # comprehensive_analysis.py - _get_likely_events
    "comp_events_help_0": "May encounter noble help and good opportunities",
    "comp_events_help_1": "Good for starting new projects or trying new things",
    "comp_events_help_2": "Smooth interpersonal relations, easy to get support",
    "comp_events_self_0": "May have important personal growth moments",
    "comp_events_self_1": "Good for establishing personal goals and direction",
    "comp_events_self_2": "May face some challenges but can overcome them",
    "comp_events_drain_0": "May feel busy with many things to do",
    "comp_events_drain_1": "Good for learning new skills to prepare for the future",
    "comp_events_drain_2": "Patience needed, results will gradually appear",
    "comp_events_attack_0": "May encounter competition or challenges",
    "comp_events_attack_1": "Good for improving personal strength",
    "comp_events_attack_2": "Need to handle interpersonal relationships well",
    "comp_events_stress_0": "May encounter some pressure or difficulties",
    "comp_events_stress_1": "Need to maintain a positive mindset",
    "comp_events_stress_2": "Best to be steady, don't be impulsive",
    "comp_events_neutral_0": "Life follows routine without major fluctuations",
    "comp_events_neutral_1": "Good for doing everyday things",
    "comp_events_neutral_2": "Keep an even keel",
    # comprehensive_analysis.py - _get_watch_out
    "comp_watch_help_0": "Good fortune but don't become overconfident",
    "comp_watch_help_1": "Cherish those who help you, don't burn bridges",
    "comp_watch_help_2": "Stay humble even during good times",
    "comp_watch_self_0": "Don't be too stubborn, learn to listen to others",
    "comp_watch_self_1": "Stay open-minded, accept different opinions",
    "comp_watch_self_2": "Pay attention to communication with family and friends",
    "comp_watch_drain_0": "Don't neglect health because of being busy",
    "comp_watch_drain_1": "Learn to prioritize, don't try to do everything",
    "comp_watch_drain_2": "Stay patient, don't rush for results",
    "comp_watch_attack_0": "Pay attention to handling interpersonal relationships",
    "comp_watch_attack_1": "Don't make impulsive decisions",
    "comp_watch_attack_2": "Stay calm, analyze rationally",
    "comp_watch_stress_0": "Pay attention to physical health, regular checkups",
    "comp_watch_stress_1": "Don't put too much pressure on yourself",
    "comp_watch_stress_2": "Learn to release stress and maintain a happy mood",
    "comp_watch_neutral_0": "Maintain good living habits",
    "comp_watch_neutral_1": "Don't become complacent because of routine",
    "comp_watch_neutral_2": "Keep learning and improving yourself",
    # comprehensive_analysis.py - _get_what_to_do
    "comp_do_help_0": "Take initiative, seize opportunities",
    "comp_do_help_1": "Expand your network, make new friends",
    "comp_do_help_2": "Try new things, challenge yourself",
    "comp_do_self_0": "Establish your goals and direction",
    "comp_do_self_1": "Stay true to yourself, don't follow the crowd",
    "comp_do_self_2": "Improve your professional skills",
    "comp_do_drain_0": "Learn new skills to prepare for the future",
    "comp_do_drain_1": "Stay patient, build steadily",
    "comp_do_drain_2": "Manage your time well, improve efficiency",
    "comp_do_attack_0": "Improve your personal strength",
    "comp_do_attack_1": "Handle interpersonal relationships well",
    "comp_do_attack_2": "Stay calm, make rational decisions",
    "comp_do_stress_0": "Maintain a positive mindset",
    "comp_do_stress_1": "Pay attention to physical health",
    "comp_do_stress_2": "Be steady, don't be impulsive",
    "comp_do_neutral_0": "Maintain good living habits",
    "comp_do_neutral_1": "Keep learning and improving yourself",
    "comp_do_neutral_2": "Cherish the people around you",
}

# Add to zh.json
with open(r'C:\Users\t\Desktop\bazi_app\static\i18n\zh.json', 'r', encoding='utf-8') as f:
    zh = json.load(f)
zh.update(zh_new_keys)
with open(r'C:\Users\t\Desktop\bazi_app\static\i18n\zh.json', 'w', encoding='utf-8') as f:
    json.dump(zh, f, ensure_ascii=False, indent=2)
print(f"zh.json: added {len(zh_new_keys)} keys, total {len(zh)} keys")

# Add to en.json
with open(r'C:\Users\t\Desktop\bazi_app\static\i18n\en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)
en.update(en_new_keys)
with open(r'C:\Users\t\Desktop\bazi_app\static\i18n\en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, ensure_ascii=False, indent=2)
print(f"en.json: added {len(en_new_keys)} keys, total {len(en)} keys")
