import json, sys, os
sys.stdout.reconfigure(encoding='utf-8')
os.chdir(os.path.dirname(__file__) or '.')

advice_translations = {
    'zh': {
        'wx_analysis_strong_fire_weak_wood': '命盘中火行最旺，火旺者性格热情、礼貌、急躁。行动力强，善于表达。木行最弱，木旺者性格仁慈、正直、有进取心。五行木偏弱。',
        'wx_analysis_balanced': '五行相对平衡，各要素分布均匀。',
        'advice_career_wood_strong': '适合教育、文化、设计等与成长相关的行业。身强者适合领导岗位。',
        'advice_career_wood_weak': '适合教育、文化、设计等与成长相关的行业。身弱者适合辅助性工作。',
        'advice_career_fire_strong': '适合能源、餐饮、演艺、互联网等需要表现力的行业。身强者适合创意岗位。',
        'advice_career_fire_weak': '适合能源、餐饮、演艺、互联网等需要表现力的行业。身弱者适合幕后工作。',
        'advice_career_earth_strong': '适合地产、建筑、管理等需要稳定的行业。身强者适合管理岗位。',
        'advice_career_earth_weak': '适合地产、建筑、管理等需要稳定的行业。身弱者适合执行岗位。',
        'advice_career_metal_strong': '适合金融、法律、审计等需要判断力的行业。身强者适合管理岗位。',
        'advice_career_metal_weak': '适合金融、法律、审计等需要判断力的行业。身弱者适合技术岗位。',
        'advice_career_water_strong': '适合物流、贸易、传媒等需要灵活的行业。身强者适合外交岗位。',
        'advice_career_water_weak': '适合物流、贸易、传媒等需要灵活的行业。身弱者适合研究岗位。',
        'advice_career_default': '根据自身特长选择行业。',
        'advice_wealth_wood': '财运与人脉和成长机会相关，适合长期投资和积累。',
        'advice_wealth_fire': '财运与表现力和社交相关，适合靠才华赚钱。',
        'advice_wealth_earth': '财运稳定，适合长期投资和不动产。',
        'advice_wealth_metal': '财运与判断力相关，适合投资和金融。',
        'advice_wealth_water': '财运灵活多变，适合贸易和流通行业。',
        'advice_wealth_default': '保持稳定收入，谨慎投资。',
        'advice_love_wood': '感情上比较主动，但有时过于固执。需要学会变通。',
        'advice_love_fire': '感情上热情奔放，但容易情绪化。需要学会冷静和包容。',
        'advice_love_earth': '感情上比较稳定，但有时表达不够浪漫。需要学会表达爱意。',
        'advice_love_metal': '感情上比较理性，不太善于表达感情。需要学会温柔。',
        'advice_love_water': '感情上比较灵活，但有时不够专一。需要学会稳定。',
        'advice_love_default': '珍惜身边的人，用心经营感情。',
        'advice_health_wood': '注意肝胆和眼睛的保养，保持情绪平和，多运动。',
        'advice_health_fire': '注意心脏和血液的保养，控制情绪，保持规律作息。',
        'advice_health_earth': '注意脾胃的保养，饮食规律，避免暴饮暴食。',
        'advice_health_metal': '注意呼吸系统的保养，避免受寒，多呼吸新鲜空气。',
        'advice_health_water': '注意肾脏的保养，保暖，避免熬夜。',
        'advice_health_default': '保持规律作息，适当运动，定期体检。',
        'advice_study_wood': '适合学习文化、教育、设计等需要创造力的学科。',
        'advice_study_fire': '适合学习传媒、艺术、互联网等需要表现力的学科。',
        'advice_study_earth': '适合学习管理、财务、建筑等需要稳定和耐心的学科。',
        'advice_study_metal': '适合学习金融、法律、计算机等需要逻辑和判断力的学科。',
        'advice_study_water': '适合学习外语、贸易、传媒等需要灵活和智慧的学科。',
        'advice_study_default': '找到自己的兴趣点，持续学习，不断进步。',
        'advice_social_wood': '社交上比较真诚，但有时过于直率。需要学会圆滑。',
        'advice_social_fire': '社交上热情开朗，人缘好。但要注意保持谦虚。',
        'advice_social_earth': '社交上比较稳重，值得信赖。但有时不够主动。',
        'advice_social_metal': '社交上比较理性。需要学会主动关心他人。',
        'advice_social_water': '社交上灵活多变，善于应变。需要保持真实。',
        'advice_social_default': '保持真诚和善良，多与人交往。',
        'advice_social_taohua': '桃花星旺，社交能力强，但要注意分辨真心。',
        'advice_social_tianyi': '天乙贵人护体，容易遇到贵人，要珍惜。',
        'advice_overall_strong_default': '命主身强，自身能量充足，适合主动出击，承担领导责任。命运掌握在自己手中。',
        'advice_overall_strong_stars_good': '命主身强，自身能量充足。命带吉星，一生有贵人相助。',
        'advice_overall_strong_stars_bad': '命主身强，自身能量充足。命带凶星，需要注意安全和防范风险。',
        'advice_overall_strong_stars_mixed': '命主身强，自身能量充足。命带吉星有贵人相助，但也有凶星需防范。',
        'advice_overall_weak_default': '命主身弱，自身能量偏弱，适合借助他人力量，团队合作。命运掌握在自己手中。',
        'advice_overall_weak_stars_good': '命主身弱，适合借助他人力量。命带吉星，一生有贵人相助。',
        'advice_overall_weak_stars_bad': '命主身弱，适合借助他人力量。命带凶星，需要注意安全和防范风险。',
        'advice_overall_weak_stars_mixed': '命主身弱，适合借助他人力量。命带吉星有贵人相助，但也有凶星需防范。',
    },
    'en': {
        'wx_analysis_strong_fire_weak_wood': 'Fire is the strongest element, making you passionate and expressive. Wood is the weakest, suggesting room for growth in creativity and planning.',
        'wx_analysis_balanced': 'The Five Elements are relatively balanced, with even distribution across all aspects.',
        'advice_career_wood_strong': 'Suited for education, culture, design. Strong Wood means leadership roles.',
        'advice_career_wood_weak': 'Suited for education, culture, design. Weaker Wood suits support roles.',
        'advice_career_fire_strong': 'Suited for energy, entertainment, internet. Strong Fire suits creative roles.',
        'advice_career_fire_weak': 'Suited for energy, entertainment, internet. Weaker Fire suits behind-the-scenes work.',
        'advice_career_earth_strong': 'Suited for real estate, construction, management. Strong Earth suits management.',
        'advice_career_earth_weak': 'Suited for real estate, construction, management. Weaker Earth suits execution roles.',
        'advice_career_metal_strong': 'Suited for finance, law, auditing. Strong Metal suits management.',
        'advice_career_metal_weak': 'Suited for finance, law, auditing. Weaker Metal suits technical roles.',
        'advice_career_water_strong': 'Suited for logistics, trade, media. Strong Water suits diplomatic roles.',
        'advice_career_water_weak': 'Suited for logistics, trade, media. Weaker Water suits research roles.',
        'advice_career_default': 'Choose a career based on your strengths.',
        'advice_wealth_wood': 'Wealth is linked to networks and growth. Focus on long-term investment.',
        'advice_wealth_fire': 'Wealth is linked to expression and social skills. Earn with your talents.',
        'advice_wealth_earth': 'Wealth is stable. Focus on long-term investment and real estate.',
        'advice_wealth_metal': 'Wealth is linked to judgment. Focus on investment and finance.',
        'advice_wealth_water': 'Wealth is flexible. Suited for trade and流通 industries.',
        'advice_wealth_default': 'Maintain stable income and invest carefully.',
        'advice_love_wood': 'Proactive in love but sometimes too stubborn. Learn to be flexible.',
        'advice_love_fire': 'Passionate in love but emotional. Learn to stay calm and tolerant.',
        'advice_love_earth': 'Stable in love but sometimes unromantic. Learn to express affection.',
        'advice_love_metal': 'Rational in love but not expressive. Learn to be gentle.',
        'advice_love_water': 'Flexible in love but sometimes unfaithful. Learn to be stable.',
        'advice_love_default': 'Cherish those around you and nurture your relationships.',
        'advice_health_wood': 'Watch liver and eye health. Stay emotionally balanced and exercise.',
        'advice_health_fire': 'Watch heart and blood health. Control emotions and maintain regular sleep.',
        'advice_health_earth': 'Watch digestive health. Eat regularly and avoid overeating.',
        'advice_health_metal': 'Watch respiratory health. Avoid cold and breathe fresh air.',
        'advice_health_water': 'Watch kidney health. Stay warm and avoid staying up late.',
        'advice_health_default': 'Maintain regular routines, exercise, and periodic checkups.',
        'advice_study_wood': 'Suited for culture, education, design — creative subjects.',
        'advice_study_fire': 'Suited for media, arts, internet — expressive subjects.',
        'advice_study_earth': 'Suited for management, finance, construction — stable subjects.',
        'advice_study_metal': 'Suited for finance, law, engineering — logical subjects.',
        'advice_study_water': 'Suited for languages, trade, media — flexible subjects.',
        'advice_study_default': 'Find your interests and keep learning.',
        'advice_social_wood': 'Sincere in socializing but sometimes too direct. Learn diplomacy.',
        'advice_social_fire': 'Warm and popular in socializing. Stay humble.',
        'advice_social_earth': 'Steady and trustworthy in socializing. Be more proactive.',
        'advice_social_metal': 'Rational in socializing. Learn to care for others.',
        'advice_social_water': 'Flexible and adaptable in socializing. Stay genuine.',
        'advice_social_default': 'Be sincere and kind, and interact with others.',
        'advice_social_taohua': ' Strong romantic charm. Be careful to distinguish genuine feelings.',
        'advice_social_tianyi': ' Noble people often help you. Cherish your benefactors.',
        'advice_overall_strong_default': 'Your Day Master is strong. Take initiative and lead. Your destiny is in your own hands.',
        'advice_overall_strong_stars_good': 'Your Day Master is strong with auspicious stars. Noble people will help you throughout life.',
        'advice_overall_strong_stars_bad': 'Your Day Master is strong, but watch for risks from inauspicious stars.',
        'advice_overall_strong_stars_mixed': 'Your Day Master is strong. Auspicious stars bring help, but watch for risks.',
        'advice_overall_weak_default': 'Your Day Master is weak. Rely on teamwork and support. Your destiny is in your own hands.',
        'advice_overall_weak_stars_good': 'Your Day Master is weak, but auspicious stars bring noble helpers.',
        'advice_overall_weak_stars_bad': 'Your Day Master is weak. Watch for risks from inauspicious stars.',
        'advice_overall_weak_stars_mixed': 'Your Day Master is weak. Stars bring both help and risk.',
    },
    'ja': {
        'wx_analysis_strong_fire_weak_wood': '火が最も強く、情熱的で表現力がある。木が最も弱く、創造力や計画性に成長の余地がある。',
        'wx_analysis_balanced': '五行は比較的バランスが取れている。',
        'advice_career_wood_strong': '教育、文化、デザインに向く。木が強めならリーダーシップ roles。',
        'advice_career_wood_weak': '教育、文化、デザインに向く。木が弱めならサポート roles。',
        'advice_career_fire_strong': 'エネルギー、エンタメ、ITに向く。火が強めならクリエイティブ。',
        'advice_career_fire_weak': 'エネルギー、エンタメ、ITに向く。火が弱めなら裏方。',
        'advice_career_earth_strong': '不動産、建設、管理に向く。土が強めなら管理職。',
        'advice_career_earth_weak': '不動産、建設、管理に向く。土が弱めなら実行職。',
        'advice_career_metal_strong': '金融、法律、監査に向く。金が強めなら管理職。',
        'advice_career_metal_weak': '金融、法律、監査に向く。金が弱めなら技術職。',
        'advice_career_water_strong': '物流、貿易、メディアに向く。水が強めなら外交。',
        'advice_career_water_weak': '物流、貿易、メディアに向く。水が弱めなら研究。',
        'advice_career_default': '自分の特技に基づいて業界を選ぼう。',
        'advice_wealth_wood': '財運は人脈と成長機会に関連。長期投資に向く。',
        'advice_wealth_fire': '財運は表現力と社交に関連。才能で稼ぐ。',
        'advice_wealth_earth': '財運は安定。長期投資と不動産に向く。',
        'advice_wealth_metal': '財運は判断力に関連。投資と金融に向く。',
        'advice_wealth_water': '財運は柔軟。貿易と流通に向く。',
        'advice_wealth_default': '安定した収入を維持し、慎重に投資。',
        'advice_love_wood': '恋愛では積極的だが、時々頑固になりがち。柔軟さを学ぼう。',
        'advice_love_fire': '恋愛では情熱的だが、感情的になりがち。冷静さと寛容さを学ぼう。',
        'advice_love_earth': '恋愛では安定しているが、時々ロマンチックではない。愛情表現を学ぼう。',
        'advice_love_metal': '恋愛では理性的で、感情表現が苦手。優しさを学ぼう。',
        'advice_love_water': '恋愛では柔軟だが、時々一途ではない。安定を学ぼう。',
        'advice_love_default': '周りの人を大切にし、愛情を持って接する。',
        'advice_health_wood': '肝臓と目の健康に注意。感情のバランスを保ち、運動を。',
        'advice_health_fire': '心臓と血液の健康に注意。感情をコントロールし、規則正しい生活を。',
        'advice_health_earth': '消化器の健康に注意。食事を規則正しくし、暴飲暴食を避ける。',
        'advice_health_metal': '呼吸器の健康に注意。寒さを避け、新鮮な空気を吸う。',
        'advice_health_water': '腎臓の健康に注意。暖かく保ち、夜更かしを避ける。',
        'advice_health_default': '規則正しい生活、適度な運動、定期健診を。',
        'advice_study_wood': '文化、教育、デザインなど創造力が必要な科目に向く。',
        'advice_study_fire': 'メディア、芸術、ITなど表現力が必要な科目に向く。',
        'advice_study_earth': '経営、財務、建設など安定と忍耐が必要な科目に向く。',
        'advice_study_metal': '金融、法律、工学など論理と判断力が必要な科目に向く。',
        'advice_study_water': '外国語、貿易、メディアなど柔軟さと知恵が必要な科目に向く。',
        'advice_study_default': '興味を見つけて、学び続けよう。',
        'advice_social_wood': '社交では素直だが、時々率直すぎる。円滑さを学ぼう。',
        'advice_social_fire': '社交では情熱的で人気。謙虚さを維持しよう。',
        'advice_social_earth': '社交では落ち着いていて信頼できる。もっと積極的に。',
        'advice_social_metal': '社交では理性的。他人を気遣うことを学ぼう。',
        'advice_social_water': '社交では柔軟で適応力がある。本物の自分を維持しよう。',
        'advice_social_default': '素直で善良になり、人と積極的に交流する。',
        'advice_social_taohua': '桃花運が強く、社交力があるが、本心を見極めよう。',
        'advice_social_tianyi': '天乙貴人が守り、出会いやすい。大切にしよう。',
        'advice_overall_strong_default': '日干が強く、エネルギーに満ちている。主体的に行動し、リーダーシップを発揮しよう。運命は自分次第。',
        'advice_overall_strong_stars_good': '日干が強く、吉星がある。一生貴人に助けられる。',
        'advice_overall_strong_stars_bad': '日干が強いが、凶星がある。安全とリスクに注意。',
        'advice_overall_strong_stars_mixed': '日干が強い。吉星で助けられるが、凶星にも注意。',
        'advice_overall_weak_default': '日干が弱く、エネルギーが不足気味。他人の力やチームワークを活用しよう。運命は自分次第。',
        'advice_overall_weak_stars_good': '日干が弱いが、吉星がある。貴人に助けられる。',
        'advice_overall_weak_stars_bad': '日干が弱く、凶星もある。リスクに注意。',
        'advice_overall_weak_stars_mixed': '日干が弱い。星が助けとリスクの両方をもたらす。',
    },
    'ko': {
        'wx_analysis_strong_fire_weak_wood': '화가 가장 강하여 열정적이고 표현력이 뛰어납니다. 목이 가장 약하여 창의력과 계획 성장 여지가 있습니다.',
        'wx_analysis_balanced': '오행이 비교적 균형 잡혀 있습니다.',
        'advice_career_wood_strong': '교육, 문화, 디자인에 적합. 목이 강하면 리더십 역할.',
        'advice_career_wood_weak': '교육, 문화, 디자인에 적합. 목이 약하면 보조 역할.',
        'advice_career_fire_strong': '에너지, 엔터테인먼트, IT에 적합. 화가 강하면 크리에이티브.',
        'advice_career_fire_weak': '에너지, 엔터테인먼트, IT에 적합. 화가 약하면 백스테이지.',
        'advice_career_earth_strong': '부동산, 건설, 경영에 적합. 토가 강하면 관리직.',
        'advice_career_earth_weak': '부동산, 건설, 경영에 적합. 토가 약하면 실행직.',
        'advice_career_metal_strong': '금융, 법률, 감사에 적합. 금이 강하면 관리직.',
        'advice_career_metal_weak': '금융, 법률, 감사에 적합. 금이 약하면 기술직.',
        'advice_career_water_strong': '물류, 무역, 미디어에 적합. 수가 강하면 외교.',
        'advice_career_water_weak': '물류, 무역, 미디어에 적합. 수가 약하면 연구.',
        'advice_career_default': '자신의 특기를 기반으로 업계를 선택하세요.',
        'advice_wealth_wood': '재운은 인맥과 성장 기회와 관련. 장기 투자에 적합.',
        'advice_wealth_fire': '재운은 표현력과 사교와 관련. 재능으로 벌기.',
        'advice_wealth_earth': '재운이 안정적. 장기 투자와 부동산에 적합.',
        'advice_wealth_metal': '재운은 판단력과 관련. 투자와 금융에 적합.',
        'advice_wealth_water': '재운이 유연함. 무역과 유통에 적합.',
        'advice_wealth_default': '안정적인 수입을 유지하고 신중하게 투자하세요.',
        'advice_love_wood': '연애에서 적극적이나 때로 고집이 셉니다. 융통성을 배우세요.',
        'advice_love_fire': '연애에서 열정적이나 감정적입니다. 냉정함과 포용을 배우세요.',
        'advice_love_earth': '연애에서 안정적이지만 때로 로맨틱하지 않습니다. 사랑 표현을 배우세요.',
        'advice_love_metal': '연애에서 이성적이나 감정 표현이 서툴니다. 다정함을 배우세요.',
        'advice_love_water': '연애에서 유연하나 때로 일관성이 부족합니다. 안정을 배우세요.',
        'advice_love_default': '주변 사람을 소중히 여기고 정성껏 사랑을 가꾸세요.',
        'advice_health_wood': '간과 눈 건강에 주의. 감정 균형을 유지하고 운동하세요.',
        'advice_health_fire': '심장과 혈액 건강에 주의. 감정을 조절하고 규칙적인 생활을.',
        'advice_health_earth': '소화기 건강에 주의. 식사를 규칙적으로 하고 과식을 피하세요.',
        'advice_health_metal': '호흡기 건강에 주의. 추위를 피하고 신선한 공기를 마시세요.',
        'advice_health_water': '신장 건강에 주의. 따뜻하게 하고 야근을 피하세요.',
        'advice_health_default': '규칙적인 생활, 적절한 운동, 정기 검진을 유지하세요.',
        'advice_study_wood': '교육, 문화, 디자인 등 창의력이 필요한 과목에 적합.',
        'advice_study_fire': '미디어, 예술, IT 등 표현력이 필요한 과목에 적합.',
        'advice_study_earth': '경영, 재무, 건설 등 안정과 인내가 필요한 과목에 적합.',
        'advice_study_metal': '금융, 법률, 공학 등 논리와 판단력이 필요한 과목에 적합.',
        'advice_study_water': '외국어, 무역, 미디어 등 유연함과 지혜가 필요한 과목에 적합.',
        'advice_study_default': '흥미를 찾고 꾸준히 배우세요.',
        'advice_social_wood': '사교에서 진심이지만 때로 너무 직설적입니다. 원만함을 배우세요.',
        'advice_social_fire': '사교에서 열정적이고 인기가 많습니다. 겸손을 유지하세요.',
        'advice_social_earth': '사교에서 차분하고 신뢰할 수 있습니다. 더 적극적으로 하세요.',
        'advice_social_metal': '사교에서 이성적입니다. 남을 돌보는 법을 배우세요.',
        'advice_social_water': '사교에서 유연하고 적응력이 좋습니다. 진심을 유지하세요.',
        'advice_social_default': '진심과 선함을 유지하고 사람들과 적극적으로 교류하세요.',
        'advice_social_taohua': '桃花運이 강하고 사교력이 좋지만 진심을 분별하세요.',
        'advice_social_tianyi': '천을귀인이 보호하여 귀인을 만나기 쉽습니다. 소중히 하세요.',
        'advice_overall_strong_default': '일간이 강하여 에너지가 충분합니다. 적극적으로 행동하고 리더십을 발휘하세요. 운명은 자신에게 달려 있습니다.',
        'advice_overall_strong_stars_good': '일간이 강하고 길성이 있습니다. 평생 귀인의 도움을 받습니다.',
        'advice_overall_strong_stars_bad': '일간이 강하지만 흉성이 있습니다. 안전과 리스크에 주의하세요.',
        'advice_overall_strong_stars_mixed': '일간이 강합니다. 길성으로 도움을 받지만 흉성도 주의하세요.',
        'advice_overall_weak_default': '일간이 약하여 에너지가 부족합니다. 타인의 힘과 팀워크를 활용하세요. 운명은 자신에게 달려 있습니다.',
        'advice_overall_weak_stars_good': '일간이 약하지만 길성이 있어 귀인의 도움을 받습니다.',
        'advice_overall_weak_stars_bad': '일간이 약하고 흉성도 있어 리스크에 주의하세요.',
        'advice_overall_weak_stars_mixed': '일간이 약합니다. 성이 도움과 리스크를 동시에 가져옵니다.',
    },
    'vi': {
        'wx_analysis_strong_fire_weak_wood': 'Hỏa là hành mạnh nhất, khiến bạn nhiệt tình và善于 biểu đạt. Mộc yếu nhất, cần phát triển thêm sáng tạo và hoạch định.',
        'wx_analysis_balanced': 'Ngũ hành tương đối cân bằng, phân bố đều.',
        'advice_career_wood_strong': 'Phù hợp giáo dục, văn hóa, thiết kế. Mộc cường hợp vai trò lãnh đạo.',
        'advice_career_wood_weak': 'Phù hợp giáo dục, văn hóa, thiết kế. Mộc nhược hợp vai trò hỗ trợ.',
        'advice_career_fire_strong': 'Phù hợp năng lượng, giải trí, internet. Hỏa cường hợp vị trí sáng tạo.',
        'advice_career_fire_weak': 'Phù hợp năng lượng, giải trí, internet. Hỏa nhược hợp vị trí hậu trường.',
        'advice_career_earth_strong': 'Phù hợp bất động sản, xây dựng, quản lý. Thổ cường hợp quản lý.',
        'advice_career_earth_weak': 'Phù hợp bất động sản, xây dựng, quản lý. Thổ nhược hợp thực thi.',
        'advice_career_metal_strong': 'Phù hợp tài chính, luật pháp, kiểm toán. Kim cường hợp quản lý.',
        'advice_career_metal_weak': 'Phù hợp tài chính, luật pháp, kiểm toán. Kim nhược hợp kỹ thuật.',
        'advice_career_water_strong': 'Phù hợp logistics, thương mại, truyền thông. Thủy cường hợp ngoại giao.',
        'advice_career_water_weak': 'Phù hợp logistics, thương mại, truyền thông. Thủy nhược hợp nghiên cứu.',
        'advice_career_default': 'Chọn ngành nghề dựa trên thế mạnh của bạn.',
        'advice_wealth_wood': 'Tài vận liên quan đến mối quan hệ và cơ hội tăng trưởng. Đầu tư dài hạn.',
        'advice_wealth_fire': 'Tài vận liên quan đến biểu đạt và xã hội. Kiếm tiền bằng tài năng.',
        'advice_wealth_earth': 'Tài vận ổn định. Đầu tư dài hạn và bất động sản.',
        'advice_wealth_metal': 'Tài vận liên quan đến phán đoán. Đầu tư và tài chính.',
        'advice_wealth_water': 'Tài vận linh hoạt. Thích hợp thương mại và lưu thông.',
        'advice_wealth_default': 'Duy trì thu nhập ổn định và đầu tư thận trọng.',
        'advice_love_wood': 'Chủ động trong tình cảm nhưng đôi khi quá cố chấp. Học sự linh hoạt.',
        'advice_love_fire': 'Nhiệt tình trong tình cảm nhưng hay xúc động. Học bình tĩnh và bao dung.',
        'advice_love_earth': 'Ổn định trong tình cảm nhưng thiếu lãng mạn. Học bày tỏ tình yêu.',
        'advice_love_metal': 'Lý trí trong tình cảm nhưng thiếu biểu đạt. Học dịu dàng.',
        'advice_love_water': 'Linh hoạt trong tình cảm nhưng thiếu chung thủy. Học sự ổn định.',
        'advice_love_default': 'Trân trọng những người bên cạnh và vun đắp tình cảm.',
        'advice_health_wood': 'Chăm sóc gan và mắt. Duy trì cân bằng cảm xúc, tập thể dục.',
        'advice_health_fire': 'Chăm sóc tim và máu. Kiểm soát cảm xúc, sinh hoạt điều độ.',
        'advice_health_earth': 'Chăm sóc tiêu hóa. Ăn uống đều đặn, tránh ăn quá nhiều.',
        'advice_health_metal': 'Chăm sóc hô hấp. Tránh lạnh, hít thở không khí trong lành.',
        'advice_health_water': 'Chăm sóc thận. Giữ ấm, tránh thức khuya.',
        'advice_health_default': 'Duy trì sinh hoạt điều độ, tập thể dục, khám sức khỏe định kỳ.',
        'advice_study_wood': 'Phù hợp văn hóa, giáo dục, thiết kế — môn học sáng tạo.',
        'advice_study_fire': 'Phù hợp truyền thông, nghệ thuật, internet — môn học biểu đạt.',
        'advice_study_earth': 'Phù hợp quản lý, tài chính, xây dựng — môn học ổn định.',
        'advice_study_metal': 'Phù hợp tài chính, luật pháp, kỹ thuật — môn học logic.',
        'advice_study_water': 'Phù hợp ngoại ngữ, thương mại, truyền thông — môn học linh hoạt.',
        'advice_study_default': 'Tìm sở thích và không ngừng học hỏi.',
        'advice_social_wood': 'Chân thành trong giao tiếp nhưng đôi khi quá thẳng thắn. Học khéo léo.',
        'advice_social_fire': 'Nhiệt tình và được yêu mến trong giao tiếp. Giữ sự khiêm tốn.',
        'advice_social_earth': 'Điềm tĩnh và đáng tin cậy. Cần chủ động hơn.',
        'advice_social_metal': 'Lý trí trong giao tiếp. Học quan tâm người khác.',
        'advice_social_water': 'Linh hoạt và thích ứng tốt. Giữ sự chân thật.',
        'advice_social_default': 'Giữ sự chân thật và lương thiện, giao tiếp với mọi người.',
        'advice_social_taohua': 'Duyên phận mạnh, giao tiếp giỏi. Phân biệt chân thật.',
        'advice_social_tianyi': 'Thiên Ất Quý Nhân hộ thân, dễ gặp quý nhân. Trân trọng.',
        'advice_overall_weak_default': 'Nhật chủ nhược, năng lượng yếu. Nên dựa vào sức mạnh tập thể. Vận mệnh nằm trong tay bạn.',
        'advice_overall_weak_stars_good': 'Nhật chủ nhược nhưng có tinh cát. Quý nhân giúp đỡ suốt đời.',
        'advice_overall_weak_stars_bad': 'Nhật chủ nhược và có tinh hung. Chú ý an toàn và rủi ro.',
        'advice_overall_weak_stars_mixed': 'Nhật chủ nhược. Tinh cát mang lại giúp đỡ, tinh hung cần đề phòng.',
        'advice_overall_strong_default': 'Nhật chủ cường, năng lượng dồi dào. Chủ động hành động và lãnh đạo. Vận mệnh nằm trong tay bạn.',
        'advice_overall_strong_stars_good': 'Nhật chủ cường và có tinh cát. Quý nhân giúp đỡ suốt đời.',
        'advice_overall_strong_stars_bad': 'Nhật chủ cường nhưng có tinh hung. Chú ý an toàn.',
        'advice_overall_strong_stars_mixed': 'Nhật chủ cường. Tinh cát mang lại giúp đỡ, tinh hung cần đề phòng.',
    },
}

for lang, trans in advice_translations.items():
    with open(f'static/i18n/{lang}.json', encoding='utf-8') as f:
        data = json.load(f)
    for k, v in trans.items():
        data[k] = v
    with open(f'static/i18n/{lang}.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f'{lang}: {len(data)} keys')
