"""initial schema

Revision ID: 6bbf4c6c45eb
Revises: 
Create Date: 2026-06-25 14:40:29.458579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbf4c6c45eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart', schema=None) as batch_op:
        batch_op.create_index('idx_chart_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_chart_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_chart_user_own', ['user_id', 'is_own'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    with op.batch_alter_table('chart', schema=None) as batch_op:
        batch_op.drop_index('idx_chart_user_own')
        batch_op.drop_index('idx_chart_user_id')
        batch_op.drop_index('idx_chart_created_at')

    # ### end Alembic commands ###
